version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000" # Map backend port
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/mern_database
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173" # Map frontend port
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  admin:
    build:
      context: ./admin
    ports:
      - "5174:5174" # Map admin panel port
    environment:
      - NODE_ENV=development
    volumes:
      - ./admin:/app
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB port
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: