
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000" # Map backend port
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://ldinitha:NSBM1234@cluster0.xqjol.mongodb.net # Use MongoDB Atlas URI
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
      - admin

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173" # Map frontend port
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app

  admin:
    build:
      context: ./admin
    ports:
      - "5174:5174" # Map admin panel port
    environment:
      - NODE_ENV=development
    volumes:
      - ./admin:/app