

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    network_mode: host #modified
    environment:
      - JWT_SECRET=greatstack
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=greatstack123
      - MONGODB_URI=mongodb+srv://ldinitha:NSBM1234@cluster0.xqjol.mongodb.net
      - CLOUDINARY_API_KEY=212221644141426
      - CLOUDINARY_SECRET_KEY=CbAk2S9TzwjM5n-_RjlaO_Ftd6Q
      - CLOUDINARY_NAME=dnnlkayzi

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    network_mode: host #modified
    environment:
      - VITE_BACKEND_URL=http://localhost:4000

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    network_mode: host #modified
    environment:
      - VITE_BACKEND_URL=http://localhost:4000
